Repository phovea/phovea_importer, pull requests merged in 2020-08, with the labels that each got.

#116 Detect boolean columns on import
  dist/phovea.js
  dist/phovea.js.map
  dist/valuetype/valuetypes.d.ts
  dist/valuetype/valuetypes.js
  dist/valuetype/valuetypes.js.map
  src/phovea.ts
  src/valuetype/valuetypes.ts
Labels: release: minor, type: feature

#118 Release 6.1.0
  dist/phovea.js
  dist/phovea.js.map
  dist/valuetype/valuetypes.d.ts
  dist/valuetype/valuetypes.js
  dist/valuetype/valuetypes.js.map
  package.json
  src/phovea.ts
  src/valuetype/valuetypes.ts
Labels: release: minor

#119 Fix Release 6.1.0
  package.json
Labels: priority: high, type: bug
