Repository phovea/phovea_importer, pull requests merged in 2020-03, with the labels that each got.

#100 Update to Typescript 3.8
  package.json
  tsconfig.json
Labels: priority: high, release: major, type: refactor

#103 Update dependencies
  package.json
Labels: dependencies, priority: medium, type: refactor

#105 Change `buildId` to `JSON.stringify(buildId)`
  webpack.config.js
Labels: priority: medium, type: refactor

#106 Release 5.0.0
  .github/CODEOWNERS
  package.json
  tsconfig.json
  webpack.config.js
Labels: release: major

#96 Migrate to jest for testing
  .circleci/config.yml
  jest.config.js
  karma.conf.js
  package.json
  src/index.ts
  tsd.d.ts
  tslint.json
  webpack.config.js
Labels: release: major, type: refactor
